"""Webhook, integration, and event dispatch models.

Provides the database schema for the Webhook & Integration Platform,
including webhook endpoint configuration, delivery tracking with retry
support, and third-party integration (Slack, Teams, PagerDuty, Jira)
configuration storage.
"""

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import ARRAY, JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.organization import Organization
    from app.models.user import User


# ── Event Types ──────────────────────────────────────────────────────────


class EventType(str, enum.Enum):
    """All event types that can trigger webhooks and integrations."""

    ALERT_CREATED = "alert.created"
    ALERT_RESOLVED = "alert.resolved"
    ALERT_ESCALATED = "alert.escalated"
    CAMERA_ONLINE = "camera.online"
    CAMERA_OFFLINE = "camera.offline"
    FACE_RECOGNIZED = "face.recognized"
    FACE_UNKNOWN = "face.unknown"
    VEHICLE_ENTRY = "vehicle.entry"
    VEHICLE_EXIT = "vehicle.exit"
    ANOMALY_DETECTED = "anomaly.detected"
    SYSTEM_HEALTH = "system.health"


EVENT_TYPE_DESCRIPTIONS: dict[str, str] = {
    EventType.ALERT_CREATED.value: "Fired when a new alert is generated by a detection rule.",
    EventType.ALERT_RESOLVED.value: "Fired when an alert is resolved or marked as false positive.",
    EventType.ALERT_ESCALATED.value: "Fired when an alert is escalated to another user.",
    EventType.CAMERA_ONLINE.value: "Fired when a camera comes back online after being offline.",
    EventType.CAMERA_OFFLINE.value: "Fired when a camera goes offline or becomes unreachable.",
    EventType.FACE_RECOGNIZED.value: "Fired when a known face is recognized by the system.",
    EventType.FACE_UNKNOWN.value: "Fired when an unknown face is detected in a restricted area.",
    EventType.VEHICLE_ENTRY.value: "Fired when a vehicle enters a monitored zone or parking area.",
    EventType.VEHICLE_EXIT.value: "Fired when a vehicle exits a monitored zone or parking area.",
    EventType.ANOMALY_DETECTED.value: "Fired when an anomalous behaviour pattern is detected.",
    EventType.SYSTEM_HEALTH.value: "Periodic system health status update.",
}

EVENT_TYPE_EXAMPLE_PAYLOADS: dict[str, dict] = {
    EventType.ALERT_CREATED.value: {
        "event": "alert.created",
        "timestamp": "2026-02-24T10:30:00Z",
        "data": {
            "alert_id": "550e8400-e29b-41d4-a716-446655440000",
            "title": "Intrusion detected in Entry Gate Zone",
            "severity": "high",
            "camera_id": "660e8400-e29b-41d4-a716-446655440001",
            "camera_name": "Main Entrance",
            "zone_name": "Entry Gate Zone",
        },
    },
    EventType.ALERT_RESOLVED.value: {
        "event": "alert.resolved",
        "timestamp": "2026-02-24T10:45:00Z",
        "data": {
            "alert_id": "550e8400-e29b-41d4-a716-446655440000",
            "resolved_by": "John Smith",
            "resolution_note": "Verified as delivery person.",
        },
    },
    EventType.ALERT_ESCALATED.value: {
        "event": "alert.escalated",
        "timestamp": "2026-02-24T10:35:00Z",
        "data": {
            "alert_id": "550e8400-e29b-41d4-a716-446655440000",
            "escalated_to": "Jane Doe",
            "reason": "Needs manager approval.",
        },
    },
    EventType.CAMERA_ONLINE.value: {
        "event": "camera.online",
        "timestamp": "2026-02-24T10:00:00Z",
        "data": {
            "camera_id": "660e8400-e29b-41d4-a716-446655440001",
            "camera_name": "Main Entrance",
            "previous_status": "offline",
        },
    },
    EventType.CAMERA_OFFLINE.value: {
        "event": "camera.offline",
        "timestamp": "2026-02-24T09:55:00Z",
        "data": {
            "camera_id": "660e8400-e29b-41d4-a716-446655440001",
            "camera_name": "Main Entrance",
            "last_seen_at": "2026-02-24T09:50:00Z",
        },
    },
    EventType.FACE_RECOGNIZED.value: {
        "event": "face.recognized",
        "timestamp": "2026-02-24T11:00:00Z",
        "data": {
            "person_id": "770e8400-e29b-41d4-a716-446655440002",
            "person_name": "Alice Johnson",
            "camera_name": "Lobby Camera",
            "confidence": 0.97,
        },
    },
    EventType.FACE_UNKNOWN.value: {
        "event": "face.unknown",
        "timestamp": "2026-02-24T11:05:00Z",
        "data": {
            "camera_name": "Server Room Entrance",
            "snapshot_url": "/snapshots/unknown_face_20260224_110500.jpg",
        },
    },
    EventType.VEHICLE_ENTRY.value: {
        "event": "vehicle.entry",
        "timestamp": "2026-02-24T08:30:00Z",
        "data": {
            "plate_number": "ABC-1234",
            "camera_name": "Parking Gate A",
            "vehicle_category": "sedan",
        },
    },
    EventType.VEHICLE_EXIT.value: {
        "event": "vehicle.exit",
        "timestamp": "2026-02-24T17:30:00Z",
        "data": {
            "plate_number": "ABC-1234",
            "camera_name": "Parking Gate A",
            "duration_minutes": 540,
        },
    },
    EventType.ANOMALY_DETECTED.value: {
        "event": "anomaly.detected",
        "timestamp": "2026-02-24T14:00:00Z",
        "data": {
            "anomaly_type": "unusual_crowd_density",
            "camera_name": "Food Court",
            "confidence": 0.85,
            "description": "Crowd density 3x above average for this time.",
        },
    },
    EventType.SYSTEM_HEALTH.value: {
        "event": "system.health",
        "timestamp": "2026-02-24T12:00:00Z",
        "data": {
            "status": "healthy",
            "cameras_online": 45,
            "cameras_offline": 2,
            "active_alerts": 12,
            "cpu_usage": 0.45,
            "memory_usage": 0.62,
        },
    },
}


# ── Delivery Status ──────────────────────────────────────────────────────


class DeliveryStatus(str, enum.Enum):
    """Status of a webhook delivery attempt."""

    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"
    RETRYING = "retrying"


# ── Integration Types ────────────────────────────────────────────────────


class IntegrationType(str, enum.Enum):
    """Supported third-party integration types."""

    SLACK = "slack"
    TEAMS = "teams"
    PAGERDUTY = "pagerduty"
    JIRA = "jira"
    CUSTOM = "custom"


# ── Webhook Endpoint ─────────────────────────────────────────────────────


class WebhookEndpoint(Base):
    """A registered webhook endpoint that receives event notifications.

    Each endpoint has a unique HMAC secret for payload signing, a list
    of subscribed event types, optional custom headers, and a
    configurable retry policy with exponential backoff.
    """

    __tablename__ = "webhook_endpoints"

    org_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    url: Mapped[str] = mapped_column(String(2048), nullable=False)
    secret: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
        doc="HMAC-SHA256 signing secret (stored encrypted).",
    )
    events: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        nullable=False,
        default=list,
        doc="List of event type strings that trigger this webhook.",
    )
    headers: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
        default=None,
        doc="Optional custom HTTP headers sent with each delivery.",
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    retry_policy: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
        default=lambda: {"max_retries": 5, "backoff_seconds": 30},
        doc="Retry policy: max_retries and initial backoff_seconds.",
    )
    created_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        doc="Soft-delete flag.",
    )

    # ── Relationships ──────────────────────────────────────────────────
    organization: Mapped["Organization"] = relationship(
        "Organization",
        lazy="selectin",
    )
    creator: Mapped[Optional["User"]] = relationship(
        "User",
        lazy="selectin",
    )
    deliveries: Mapped[List["WebhookDelivery"]] = relationship(
        "WebhookDelivery",
        back_populates="webhook",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    def __repr__(self) -> str:
        return f"<WebhookEndpoint(id={self.id}, name='{self.name}', url='{self.url[:50]}...')>"


# ── Webhook Delivery ─────────────────────────────────────────────────────


class WebhookDelivery(Base):
    """Record of a single webhook delivery attempt.

    Tracks the payload, HTTP response, retry state, and timing for
    each delivery to a webhook endpoint. Failed deliveries are retried
    according to the parent endpoint's retry policy.
    """

    __tablename__ = "webhook_deliverys"

    webhook_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("webhook_endpoints.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    event_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
    )
    payload: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
    )
    status: Mapped[DeliveryStatus] = mapped_column(
        String(32),
        nullable=False,
        default=DeliveryStatus.PENDING,
        server_default=DeliveryStatus.PENDING.value,
    )
    status_code: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        doc="HTTP status code from the endpoint response.",
    )
    response_body: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Truncated response body (max 4096 chars).",
    )
    attempt_number: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
    )
    next_retry_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="Scheduled time for next retry attempt.",
    )
    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Error description if delivery failed.",
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="Timestamp when delivery completed (success or final failure).",
    )

    # ── Relationships ──────────────────────────────────────────────────
    webhook: Mapped["WebhookEndpoint"] = relationship(
        "WebhookEndpoint",
        back_populates="deliveries",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return (
            f"<WebhookDelivery(id={self.id}, webhook_id={self.webhook_id}, "
            f"event={self.event_type}, status={self.status.value})>"
        )


# ── Integration Config ───────────────────────────────────────────────────


class IntegrationConfig(Base):
    """Configuration for a third-party integration (Slack, Teams, etc.).

    Stores the integration type, a human-readable name, and a JSONB
    configuration blob holding credentials and channel/project details.
    The config column should be encrypted at the application layer
    before persistence.
    """

    __tablename__ = "integration_configs"

    org_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    integration_type: Mapped[IntegrationType] = mapped_column(
        String(32),
        nullable=False,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    config: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        doc="Integration-specific configuration (encrypted at app layer).",
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )
    created_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        doc="Soft-delete flag.",
    )

    # ── Relationships ──────────────────────────────────────────────────
    organization: Mapped["Organization"] = relationship(
        "Organization",
        lazy="selectin",
    )
    creator: Mapped[Optional["User"]] = relationship(
        "User",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return (
            f"<IntegrationConfig(id={self.id}, type={self.integration_type.value}, "
            f"name='{self.name}')>"
        )
