"""
Zone Analyzer for VisionAI.

Provides spatial analytics including zone intrusion detection (point-in-
polygon), tripwire line crossing detection, and zone occupancy counting.

Zones are defined as polygons in normalised ``[0, 1]`` coordinates or
pixel coordinates.  Tripwires are defined as line segments.

Usage::

    from app.cv.analyzers.zone_analyzer import ZoneAnalyzer

    analyzer = ZoneAnalyzer()
    analyzer.add_zone("entry", [(100, 100), (400, 100), (400, 400), (100, 400)])
    results = analyzer.check_detections(detections)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import structlog

logger = structlog.stdlib.get_logger(__name__)


@dataclass
class ZoneDefinition:
    """Definition of a spatial zone.

    Attributes:
        zone_id: Unique zone identifier.
        name: Human-readable zone name.
        polygon: List of polygon vertices as ``[(x, y), ...]`` in pixel
            coordinates.
        zone_type: Type of zone (``"inclusion"``, ``"exclusion"``,
            ``"restricted"``).
        max_occupancy: Optional maximum allowed occupancy.
    """

    zone_id: str
    name: str
    polygon: list[tuple[float, float]]
    zone_type: str = "inclusion"
    max_occupancy: Optional[int] = None


@dataclass
class TripwireDefinition:
    """Definition of a tripwire line.

    Attributes:
        wire_id: Unique tripwire identifier.
        name: Human-readable name.
        start: Line start point as ``(x, y)``.
        end: Line end point as ``(x, y)``.
        direction: Expected crossing direction for alerts
            (``"left_to_right"``, ``"right_to_left"``, ``"both"``).
    """

    wire_id: str
    name: str
    start: tuple[float, float]
    end: tuple[float, float]
    direction: str = "both"


@dataclass
class ZoneEvent:
    """Event generated by zone analysis.

    Attributes:
        zone_id: Zone or tripwire identifier.
        zone_name: Human-readable name.
        event_type: Type of event (``"intrusion"``, ``"crossing"``,
            ``"overcrowding"``).
        track_id: Track identifier of the triggering object.
        details: Additional event details.
    """

    zone_id: str
    zone_name: str
    event_type: str
    track_id: Optional[int] = None
    details: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Serialise to a plain dictionary."""
        return {
            "zone_id": self.zone_id,
            "zone_name": self.zone_name,
            "event_type": self.event_type,
            "track_id": self.track_id,
            "details": self.details,
        }


class ZoneAnalyzer:
    """Spatial zone and tripwire analysis engine.

    Maintains a set of defined zones and tripwires, checks detection
    positions against them, and generates events for intrusions and
    line crossings.
    """

    def __init__(self) -> None:
        self.zones: dict[str, ZoneDefinition] = {}
        self.tripwires: dict[str, TripwireDefinition] = {}
        # Track previous positions for tripwire crossing detection
        self._previous_positions: dict[int, tuple[float, float]] = {}

        logger.info("zone_analyzer.initialised")

    def add_zone(
        self,
        zone_id: str,
        polygon: list[tuple[float, float]],
        name: str = "",
        zone_type: str = "inclusion",
        max_occupancy: int | None = None,
    ) -> None:
        """Add a zone definition.

        Args:
            zone_id: Unique zone identifier.
            polygon: Polygon vertices as ``[(x, y), ...]``.
            name: Human-readable zone name.
            zone_type: Zone type.
            max_occupancy: Optional occupancy limit.
        """
        self.zones[zone_id] = ZoneDefinition(
            zone_id=zone_id,
            name=name or zone_id,
            polygon=polygon,
            zone_type=zone_type,
            max_occupancy=max_occupancy,
        )
        logger.debug("zone_analyzer.zone_added", zone_id=zone_id, vertices=len(polygon))

    def add_tripwire(
        self,
        wire_id: str,
        start: tuple[float, float],
        end: tuple[float, float],
        name: str = "",
        direction: str = "both",
    ) -> None:
        """Add a tripwire definition.

        Args:
            wire_id: Unique tripwire identifier.
            start: Line start point ``(x, y)``.
            end: Line end point ``(x, y)``.
            name: Human-readable name.
            direction: Expected crossing direction.
        """
        self.tripwires[wire_id] = TripwireDefinition(
            wire_id=wire_id,
            name=name or wire_id,
            start=start,
            end=end,
            direction=direction,
        )
        logger.debug("zone_analyzer.tripwire_added", wire_id=wire_id)

    def remove_zone(self, zone_id: str) -> None:
        """Remove a zone definition."""
        self.zones.pop(zone_id, None)

    def remove_tripwire(self, wire_id: str) -> None:
        """Remove a tripwire definition."""
        self.tripwires.pop(wire_id, None)

    def check_detections(
        self,
        detections: list[dict],
    ) -> list[ZoneEvent]:
        """Check a list of detections against all zones for intrusion.

        Each detection should have a ``center`` or ``bbox`` key.
        A detection is considered inside a zone if its centre point
        falls within the zone polygon.

        Args:
            detections: List of detection dictionaries.  Expected keys:
                - ``bbox``: ``[x1, y1, x2, y2]``
                - ``track_id`` (optional): Integer tracker ID.
                - ``class_name`` (optional): Detection class.

        Returns:
            list[ZoneEvent]: Intrusion events for detections inside
                exclusion or restricted zones.
        """
        events: list[ZoneEvent] = []

        for det in detections:
            bbox = det.get("bbox")
            if bbox is None:
                continue

            # Compute centre point
            cx = (bbox[0] + bbox[2]) / 2.0
            cy = (bbox[1] + bbox[3]) / 2.0
            point = (cx, cy)
            track_id = det.get("track_id")

            for zone in self.zones.values():
                if self._point_in_polygon(point, zone.polygon):
                    if zone.zone_type in ("exclusion", "restricted"):
                        events.append(ZoneEvent(
                            zone_id=zone.zone_id,
                            zone_name=zone.name,
                            event_type="intrusion",
                            track_id=track_id,
                            details={
                                "point": list(point),
                                "zone_type": zone.zone_type,
                                "class_name": det.get("class_name", "unknown"),
                            },
                        ))

        return events

    def check_tripwire(
        self,
        tracked_objects: list[dict],
    ) -> list[ZoneEvent]:
        """Check tracked objects for tripwire line crossings.

        Uses the object's previous and current positions to detect
        whether the movement path intersects any tripwire.

        Args:
            tracked_objects: List of tracked object dictionaries.
                Expected keys:
                - ``track_id``: Integer tracker ID.
                - ``bbox``: ``[x1, y1, x2, y2]``.

        Returns:
            list[ZoneEvent]: Crossing events.
        """
        events: list[ZoneEvent] = []

        for obj in tracked_objects:
            track_id = obj.get("track_id")
            bbox = obj.get("bbox")
            if track_id is None or bbox is None:
                continue

            cx = (bbox[0] + bbox[2]) / 2.0
            cy = (bbox[1] + bbox[3]) / 2.0
            curr_pos = (cx, cy)

            prev_pos = self._previous_positions.get(track_id)
            self._previous_positions[track_id] = curr_pos

            if prev_pos is None:
                continue

            for wire in self.tripwires.values():
                crossing = self._check_line_crossing(
                    prev_pos, curr_pos, wire.start, wire.end,
                )
                if crossing is not None:
                    # Check direction filter
                    if wire.direction != "both" and crossing != wire.direction:
                        continue

                    events.append(ZoneEvent(
                        zone_id=wire.wire_id,
                        zone_name=wire.name,
                        event_type="crossing",
                        track_id=track_id,
                        details={
                            "direction": crossing,
                            "prev_pos": list(prev_pos),
                            "curr_pos": list(curr_pos),
                        },
                    ))

        return events

    def get_zone_occupancy(
        self,
        detections: list[dict],
    ) -> dict[str, dict]:
        """Count the number of detections in each zone.

        Args:
            detections: List of detection dictionaries with ``bbox``.

        Returns:
            dict[str, dict]: Per-zone occupancy information with keys:
                - ``count``: Number of detections in the zone.
                - ``max_occupancy``: Configured limit (or ``None``).
                - ``overcrowded``: ``True`` if limit is exceeded.
                - ``track_ids``: List of track IDs in the zone.
        """
        occupancy: dict[str, dict] = {}

        for zone in self.zones.values():
            count = 0
            track_ids: list[int] = []

            for det in detections:
                bbox = det.get("bbox")
                if bbox is None:
                    continue

                cx = (bbox[0] + bbox[2]) / 2.0
                cy = (bbox[1] + bbox[3]) / 2.0

                if self._point_in_polygon((cx, cy), zone.polygon):
                    count += 1
                    tid = det.get("track_id")
                    if tid is not None:
                        track_ids.append(tid)

            overcrowded = (
                zone.max_occupancy is not None
                and count > zone.max_occupancy
            )

            occupancy[zone.zone_id] = {
                "name": zone.name,
                "count": count,
                "max_occupancy": zone.max_occupancy,
                "overcrowded": overcrowded,
                "track_ids": track_ids,
            }

        return occupancy

    def cleanup_tracks(self, active_track_ids: set[int]) -> None:
        """Remove position history for tracks no longer active.

        Args:
            active_track_ids: Set of currently active track IDs.
        """
        stale = [
            tid for tid in self._previous_positions
            if tid not in active_track_ids
        ]
        for tid in stale:
            del self._previous_positions[tid]

    @staticmethod
    def _point_in_polygon(
        point: tuple[float, float],
        polygon: list[tuple[float, float]],
    ) -> bool:
        """Test whether a point lies inside a polygon (ray casting).

        Args:
            point: Test point ``(x, y)``.
            polygon: Polygon vertices ``[(x, y), ...]``.

        Returns:
            bool: ``True`` if inside.
        """
        if len(polygon) < 3:
            return False

        px, py = point
        n = len(polygon)
        inside = False

        j = n - 1
        for i in range(n):
            xi, yi = polygon[i]
            xj, yj = polygon[j]

            if ((yi > py) != (yj > py)) and (
                px < (xj - xi) * (py - yi) / (yj - yi) + xi
            ):
                inside = not inside
            j = i

        return inside

    @staticmethod
    def _check_line_crossing(
        prev_pos: tuple[float, float],
        curr_pos: tuple[float, float],
        line_start: tuple[float, float],
        line_end: tuple[float, float],
    ) -> Optional[str]:
        """Check if a movement segment crosses a line segment.

        Args:
            prev_pos: Previous position ``(x, y)``.
            curr_pos: Current position ``(x, y)``.
            line_start: Line start point ``(x, y)``.
            line_end: Line end point ``(x, y)``.

        Returns:
            Optional[str]: Crossing direction or ``None``.
        """
        # Parametric line intersection
        x1, y1 = prev_pos
        x2, y2 = curr_pos
        x3, y3 = line_start
        x4, y4 = line_end

        denom = (x1 - x2) * (y3 - y4) - (y1 - y2) * (x3 - x4)
        if abs(denom) < 1e-10:
            return None

        t = ((x1 - x3) * (y3 - y4) - (y1 - y3) * (x3 - x4)) / denom
        u = -((x1 - x2) * (y1 - y3) - (y1 - y2) * (x1 - x3)) / denom

        if not (0.0 <= t <= 1.0 and 0.0 <= u <= 1.0):
            return None

        # Determine crossing direction via cross product
        lx = x4 - x3
        ly = y4 - y3
        px = x1 - x3
        py = y1 - y3
        cross = lx * py - ly * px

        if cross > 0:
            return "left_to_right"
        elif cross < 0:
            return "right_to_left"
        return None
